#!/bin/bash
sudo apt remove --purge rpicam-apps
sudo apt install -y libcamera-dev libepoxy-dev libjpeg-dev libtiff5-dev libpng-dev
sudo apt install -y qtbase5-dev libqt5core5a libqt5gui5 libqt5widgets5
sudo apt install libavcodec-dev libavdevice-dev libavformat-dev libswresample-dev
sudo apt install -y cmake libboost-program-options-dev libdrm-dev libexif-dev
sudo apt install -y meson ninja-build libboost-dev

rm -rf build
meson setup build --buildtype=debug -Denable_libav=enabled -Denable_drm=enabled -Denable_egl=enabled -Denable_qt=enabled -Denable_opencv=disabled -Denable_tflite=disabled -Denable_hailo=enabled | tee setup.log

meson compile -C build --verbose | tee build.log

sudo ninja -C build --verbose  install | tee install.log

sudo ldconfig
rpicam-still --version
